name: "individual task ci"

on: push

jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: main dir
        run: pwd

      - name: gcc install
        run: |
          sudo apt-get update && sudo apt-get install -y gcc g++
          which gcc

      - name: cmake install
        run: |
          sudo apt-get update && sudo apt-get install -y cmake
          which cmake

      - name: cpplint install
        run: |
          sudo apt-get update && sudo pip install cpplint
          which cpplint

  building:
    runs-on: ubuntu-latest
    needs: [checking]
    steps:

      - uses: actions/checkout@v2
      - name: WORKING DIRECTORY
        run: pwd

      - name: INSTALL GCC
        run: |
          sudo apt-get update && sudo apt-get install -y gcc g++
          which gcc

      - name: INSTALL CMAKE
        run: |
          sudo apt-get update && sudo apt-get install -y cmake
          which cmake

      - name: INSTALL VALGRIND
        run: |
          sudo apt-get update && sudo apt-get install -y valgrind
          which valgrind

  testing:
    runs-on: ubuntu-latest
    needs: [building]
    steps:

      - uses: actions/checkout@v2
      - name: WORKING DIRECTORY
        run: pwd

      - name: INSTALL GCC
        run: |
          sudo apt-get update && sudo apt-get install -y gcc g++
          which gcc

      - name: INSTALL CMAKE
        run: |
          sudo apt-get update && sudo apt-get install -y cmake
          which cmake

      - name: INSTALL LCOV
        run: |
          sudo apt-get update && sudo apt-get install -y lcov
          which lcov

      - name: INSTALL PIP
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          which python3
          which pip

      - name: INSTALL VALGRIND
        run: |
          sudo apt-get update && sudo apt-get install -y valgrind
          which valgrind

      - name: INSTALL GTEST
        run:  |
          git clone https://github.com/google/googletest
          pwd
          cd ./googletest
          pwd
          mkdir -p build && cd build
          sudo cmake ..
          sudo make
          sudo make install
          cd ../../
          pwd
      - name: run gtest
        run: |
          mkdir -p build && cd build
          cmake ..
          make
          ctest