name: 'individual task ci'

on:
  push:
  pull-request:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'run gtest'
        run: cd ~/build/ && cmake .. && make && ctest
